.\"  SPDX-License-Identifier: LGPL-3.0-or-later
.\"  SPDX-FileCopyrightText: 2020, Western Digital Corporation or its affiliates.
.\"  Written by Damien Le Moal <damien.lemoal@wdc.com>
.\"
.TH ZBC 8
.SH NAME
zbc_write_zone \- Write sectors to a zone of a ZBC or ZAC device

.SH SYNOPSIS
.B zbc_write_zone
[options]
.IR device
.IR zone_number
.IR IO_size

.SH DESCRIPTION
.B zbc_write_zone
is used to write sectors to a zone of a ZBC or ZAC device. By default, the
target zone will be written starting from the first sector of the zone for
conventional zones and from the zone write pointer position for sequential
zones. The default behavior is to write up to the last sector of the target
zone.

.PP
The
.I device
argument must be the pathname to the target device block device file (e.g.,
.IR /dev/sdb "),"
or to the target device SG node file (e.g.,
.IR /dev/sg3 ")."
On old kernels lacking ZBC and ZAC support, only the device SG node file will
be available.

.SH OPTIONS
The following options can be specified.
.TP
.BR \-h , " \-\-help"
Display a usage help message and exit.
.TP
.BR \-v
Verbose mode (for debugging problems).
.TP
.BR \-dio
Use direct IO operations.
.TP
.BR \-vio " " \fInum\fR
Use vectored I/Os with \fBnum\fR buffers of
.I IO_size
bytes, resulting in an actual I/O size of \fBnum\fR x
.I IO_size
bytes.
.TP
.BR \-nio " " \fInum\fR
Limit the number of I/O executed to \fBnum\fR.
.TP
.BR \-p " " \fInum\fR
Set the byte values to write to \fBnum\fR. If this option is not used,
zeroes are written to the target zone.
.TP
.BR \-f " " \fIfile\fR
Write the content of \fBfile\fR to the target zone.
.TP
.BR \-loop
If a file is specified with the option \fB-f\fR, repeatedly write the
content of the file to the zone until the zone is full.
.TP
.BR \-ofst " " \fIofst\fR
Write the target zone starting from the sector offset \fBofst\fR instead
of from the start of the zone. This option should be used only with
conventional zones.

.SH AUTHOR
.nf
Damien Le Moal <damien.lemoal@wdc.com>
.fi

.SH SEE ALSO
.na
.BR sg_dd (8)
.ad

.SH AVAILABILITY
The \fBzbc_write_zone\fP utility is part of the \fBlibzbc\fP library available
from
.UR https://\:github.com\:/westerndigitalcorporation\:/libzbc
.UE .
